name: "Testing all apps"

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
      - name: pnpm install recursive
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.17.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Testing Nuxt 2
        run: pnpm run test:nuxt2

      - name: Testing Vue 2
        run: pnpm run test:vue2

      - name: Testing Vue 3
        run: pnpm run test:vue3
